export BROWSER="/usr/bin/firefox"
export EDITOR="/usr/bin/vim"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export INSTALL4J_ADD_VM_PARAMS="-Dglass.gtk.uiScale=2.0"
export KUBECONFIG="$HOME/.kube/config.lh"
export QT_QPA_PLATFORMTHEME="qt5ct"
