[theme]
theme = "semi-native"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
format = " $icon  $utilization.eng(width:1) $barchart "
interval = 1

[[block]]
block = "load"
format = " $icon  $1m.eng(width:4) $5m.eng(width:4) $15m.eng(width:4) "
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents $mem_free "

# [[block]]
# block = "net"
# format = " $icon  $signal_strength "

# [[block]]
# block = "speedtest"
# format = " ^icon_ping $ping ^icon_net_down $speed_down ^icon_net_up $speed_up "

[[block]]
block = "disk_space"
format = " $icon $available "
interval = 10
alert = 2.5
warning = 5

[[block]]
block = "temperature"
format = " $icon $average/$max "
interval = 1

[[block]]
block = "battery"
format = " $icon $percentage $time "
interval = 1

[[block]]
block = "sound"
format = " $icon $volume "

[[block]]
block = "time"
interval = 1
format = " $icon  $timestamp.datetime(f:'%a %e %b %R') "
