"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 5000

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$ruby\
[](fg:color_blue bg:color_bg3)\
$cmd_duration\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[character]
disabled = false
error_symbol = '[](bold fg:color_red)'
success_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[cmd_duration]
format = '[[ $duration ](fg:#83a598 bg:color_bg3)]($style)'
min_time = 1000
style = 'bg:color_bg3'

[directory]
format = '[ $path ]($style)'
style = 'fg:color_fg0 bg:color_yellow'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ''
'Music'     = '󰝚'
'Pictures'  = ''
'code'      = '󰲋'

[git_branch]
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
style = 'bg:color_aqua'
symbol = ''

[git_status]
format = '[[($ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
style = 'bg:color_aqua'

[line_break]
disabled = false

[os]
disabled = false
style = 'bg:color_orange fg:color_fg0'

[os.symbols]
Arch = '󰣇'
Macos = '󰀵'

[palettes.gruvbox_dark]
color_aqua = '#689d6a'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_fg0 = '#fbf1c7'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[ruby]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = 'bg:color_blue'
symbol = ''
version_format = '$raw'

[time]
disabled = false
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'
style = 'bg:color_bg1'
time_format = '%R'
utc_time_offset = '0'

[username]
format = '[ $user ]($style)'
show_always = true
style_root = 'bg:color_orange fg:color_fg0'
style_user = 'bg:color_orange fg:color_fg0'
